export const ENCHANTMENTS = new Set([
    "Aqua Affinity",
    "Bane of Arthropods",
    "Blast Protection",
    "Breach",
    "Channeling",
    "Cleaving",
    "Curse of Binding",
    "Curse of Vanishing",
    "Density",
    "Depth Strider",
    "Efficiency",
    "Feather Falling",
    "Fire Aspect",
    "Fire Protection",
    "Flame",
    "Fortune",
    "Frost Walker",
    "Impaling",
    "Infinity",
    "Knockback",
    "Looting",
    "Loyalty",
    "Luck of the Sea",
    "Lunge",
    "Lure",
    "Mending",
    "Multishot",
    "Piercing",
    "Potatofication",
    "Power",
    "Projectile Protection",
    "Protection",
    "Punch",
    "Quick Charge",
    "Respiration",
    "Riptide",
    "Sharpness",
    "Silk Touch",
    "Smite",
    "Soul Speed",
    "Sweeping Edge",
    "Swift Sneak",
    "Thorns",
    "Unbreaking",
    "Wind Burst",
]);

export function isItemAnEnchantment(label: string): boolean {
    return ENCHANTMENTS.has(label);
}